### ISSUE TITLE
String value equality ignores quotes

### ISSUE THREAD

**Issue by pbtura** [skyscreamer/JSONassert#178]
When doing equality assertions, JSONAssert considers quoted an unquoted strings to be equal. So for example assertEquals("abc", "\"abc\"") would pass. Unquoted strings should either be throw an error for invalid json, or at the very least fail equality when compared against a quoted string.

Example code:
```
    @Test
    public void testJsonString()
    {
        String expected = "{ \"value\": \"abc\"}";
        String actual = "{\"value\": abc}";
        System.out.println(expected);
        System.out.println(actual);
        //this assertion should fail but it will pass
        JSONAssert.assertEquals( expected, actual, true);
    }
```

**Comment by carterpage** [comment]
This is the behavior of the underlying JSON library and not JSONAssert itself.
