### ISSUE TITLE
Is it possible to make it case INSENSITIVE

### ISSUE THREAD

**Issue by yhjhoo** [skyscreamer/JSONassert#184]
Is there a feature to compare the json of ignoring field name insensitive

JSONAssert.assertEquals(
      "{name: test}",
      "{Name: test}"
  )

**Comment by carterpage** [comment]
While some languages handle it differently, JSON is case sensitive. This is true in Crockford's reference implementation and the [JSON-RPC spec](https://jsonrpc.org/historical/json-rpc-1-1-alt.html#service-procedure-and-parameter-names).

If you really need it, you could write something to force all of your keys to lowercase before running the test.
