### ISSUE TITLE
Add support for current unsupported tests

### ISSUE THREAD

**Issue by carterpage** [skyscreamer/JSONassert#2]
Currently non-strict checking of a few cases are not supported:
- Array of arrays
- Arrays containing a mix of simple and complex types
- Arrays containing objects that have no unique ID's

Add support for these cases, and update the unit tests.

**Comment by Naveen1836** [comment]
Hi,

i have array of arrays, but the child arrays order is also not consistent . How do i validate ignoring order of child order.
Thanks in advance.
