### ISSUE TITLE
Fix numerical comparisons

### ISSUE THREAD

**Issue by derrickburns** [skyscreamer/JSONassert#23]
If a field appears to be an integer, and a double of the same value appears, JsonAssert reports something like:

Values of geo.coordinates[0] have different types: expected java.lang.Integer, but got java.lang.Double ; Values of geo.coordinates[1] have different types: expected java.lang.Integer, but got java.lang.Double

In this case, the value expected value is 0 (an integer) and the given value is 0.0 (a double).

The key observation is that the double can be coerced into the integer without loss of precision, and therefore should be allowed.

**Comment by smoosh911** [comment]
This issue still exists when you use the assertEquals(JSONObject, JSONObject) overload.
```JSONObject response = (JSONObject)JSONParser.parseJSON(responseString);
    		JSONObject baseline = (JSONObject)JSONParser.parseJSON(baseLineString);
    		JSONAssert.assertEquals(baseline.toString(), response.toString(), JSONCompareMode.LENIENT);```

**Comment by downloadpizza** [comment]
@smoosh911 may want to open this as its own issue, I've also run into it but don't have the time to open one right now. If I remember then I will open an issue at some point.
