### ISSUE TITLE
Add message to JSONAssert

### ISSUE THREAD

**Issue by paolodm** [skyscreamer/JSONassert#42]
I would love to be able to include a message to JSONAssert.assertEquals in the beginning of the method invocation:

``` java
assertEquals("expected should equal actual", expected, actual, false);
```

**Comment by MathieuLorber** [comment]
+1, it would be useful, and is the "standard" api for assertions

**Comment by carterpage** [comment]
I'm open to a pull request that does this.

A quick work-around could be to create a simple wrapper method that does this, and call it instead of JSONAssert directly.

**Comment by yasin3061** [comment]
@carterpage, I am on it. Will create a PR.

**Comment by carterpage** [comment]
Please ping this thread when ready. Thanks.

**Comment by yasin3061** [comment]
@carterpage - it's done. Please review the PR: https://github.com/skyscreamer/JSONassert/pull/78
