### ISSUE TITLE
Feature request: Add support for JSONP

### ISSUE THREAD

**Issue by selbekk** [skyscreamer/JSONassert#46]
Our application has both JSON and JSONP strings to verify. Could you please implement support for handling jsonp callbacks as well? I can't imagine it's very difficult, and there's not really any comparable frameworks out there.

**Comment by selbekk** [comment]
Bump!

**Comment by carterpage** [comment]
I'm not exploring supporting other formats in JSONAssert, but you could try unwrapping your JSONP callback into JSON then compare it in JSONAssert.
