### ISSUE TITLE
JSONCompareResult.getFieldFailures() does not return missing attributes

### ISSUE THREAD

**Issue by dhawken** [skyscreamer/JSONassert#51]
If an attribute is missing, the comparison will fail and the field will be returned on the message:
"Expected: <attribute> but none found".

However, this field is not included on the list of field failures from getFieldFailures().

Is this expected?

This is in STRICT mode. The missing() method does not appear to be adding anything to the _fieldFailures list.

**Comment by dhawken** [comment]
There is a PR to address this: #50

**Comment by carterpage** [comment]
Pushed in 1.3.0.
