### ISSUE TITLE
Number comparision broken when having decimals

### ISSUE THREAD

**Issue by alexanderkjall** [skyscreamer/JSONassert#55]
I have this code:

```
String expected =
            "{\"priceOffers\":[" +
                "{\"name\":\"HELTHJEM\",\"price\":{" +
                    "\"freightPrice\":{\"exclVAT\":\"23.00\",\"inclVAT\":\"28.75\",\"VAT\":\"5.75\"}," +
                    "\"customerPrice\":{\"exclVAT\":\"19.20\",\"inclVAT\":\"24.00\",\"VAT\":\"4.80\"}},\"servicePoints\":null}," +
                "{\"name\":\"POSTNORD\",\"price\":{" +
                    "\"freightPrice\":{\"exclVAT\":\"25.00\",\"inclVAT\":\"31.25\",\"VAT\":\"6.25\"}," +
                    "\"customerPrice\":{\"exclVAT\":\"20.80\",\"inclVAT\":\"26.00\",\"VAT\":\"5.20\"}},\"servicePoints\":null}]," +
            "\"statusMessages\":{}}";

JSONAssert.assertEquals(expected, ok.readEntity(String.class), false);
```

And that gives the following error messages:

priceOffers[name=POSTNORD].price.customerPrice.VAT
Expected: 5.20
     got: 5,20
 ; priceOffers[name=POSTNORD].price.customerPrice.exclVAT
Expected: 20.80
     got: 20,80
 ; priceOffers[name=POSTNORD].price.customerPrice.inclVAT
Expected: 26.00
     got: 26,00
 ; priceOffers[name=POSTNORD].price.freightPrice.VAT
Expected: 6.25
     got: 6,25
 ; priceOffers[name=POSTNORD].price.freightPrice.exclVAT
Expected: 25.00
     got: 25,00
 ; priceOffers[name=POSTNORD].price.freightPrice.inclVAT
Expected: 31.25
     got: 31,25

If I compare the raw string representations of the input and the output they are equal.

**Comment by carterpage** [comment]
I can't see the original, so I can't really compare. In your expected code the numbers are in quotes, so it's treating them as strings. From the error code, it appears your original doesn't have quotes and it's parsing them as #s.

**Comment by alexanderkjall** [comment]
This was a stupid error, I just verified with my code and you are right. Sorry for the extra work.

**Comment by carterpage** [comment]
Np. Glad you got it figured out.
