### ISSUE TITLE
JsonAssert.assertEquals Faliure 

### ISSUE THREAD

**Issue by adityagautam** [skyscreamer/JSONassert#64]
Error that I am getting:
While the values of both the strings are same. but still assertion is failing.
Expected: a JSON object but none found

Code: 
JSONParser parser = new JSONParser();
        try

```
    {

      JSONArray jsonArray = (JSONArray) parser.parse(new FileReader("/path_to_file"));

       String abc = jsonArray.toJSONString();


        Headers allHeaders = response.getHeaders();
        Gson gson = new Gson();
        String headerList = gson.toJson(allHeaders.getList("Session"));
        JSONArray jsonArray2 = (JSONArray) parser.parse(headerList);
        String abcd = jsonArray2.toJSONString();
```

JSONAssert.assertEquals(abc,abcd,false);

**Comment by carterpage** [comment]
Not sure what you're actually comparing. Try printing out abc and abcd, create code compare the raw strings (String abc = "...") and add here. That will be easier to troubleshoot.

**Comment by carterpage** [comment]
Going to close, but feel free to reopen with the actual strings if you still haven't resolved this.
