### ISSUE TITLE
Regex validation in json?

### ISSUE THREAD

**Issue by picimako** [skyscreamer/JSONassert#84]
Hi,

I have a scenario where the json that I want to compare against contains some fields with varying values like an asset path with a version number or a date in the path e.g.:
```json
{
      "href": "https://my.website.com/some/path/with/date/20170306.xml",
      "title": "Some title"
}
```

or

```json
{
      "href": "https://some.cdn-server.com/assets/3.0/carousel_button.png",
      "title": "Some title"
}
```

In the expected json file I would like to handle them as regex, so by defining the expected value as the following, and having the respective fields marked with something that reflects that it is a regex:
```json
{
      "href": "<regex>https://some.cdn-server.com/assets/\d+\.\d/carousel_button.png",
      "title": "Some title"
}
```
Then it wouldn't do an exact match comparison on them, rather a regex pattern match.

Is something like this achievable currently, maybe via `Customization`?
The naive approach would be to extend `DefaultComparator` and add the custom check into the `compareValues` method but I hope there is a more sophisticated solution than that.

**Comment by rpyaset** [comment]
@picimako you should be able to do this:

```
JSONAssert.assertEquals(expected, actual, new CustomComparator(JSONCompareMode.LENIENT, 
         new Customization(xpathExpression, new RegularExpressionValueMatcher(regex))
));
```
